fix: float arguments in host function parameters
There was a small typo in _convert_value which logged an error whenever
a host function with float argument was called:

    Exception ignored from cffi callback <function handle_args at 0x7fee3735b480>:
    Traceback (most recent call last):
      File ".../extism/extism.py", line 908, in handle_args
        inp.append(_convert_value(inputs[i]))
      File ".../extism/extism.py", line 648, in _convert_value
        elif x.y == 3:
    AttributeError: cdata 'ExtismVal' has no field 'y'